<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="TestAll" duration-ms="97620" started-at="2014-09-10T10:37:01Z" finished-at="2014-09-10T10:38:39Z">
    <groups>
    </groups>
    <test name="order3" duration-ms="97620" started-at="2014-09-10T10:37:01Z" finished-at="2014-09-10T10:38:39Z">
      <class name="prog.Facebook">
        <test-method status="FAIL" signature="testYahooTest()[pri:0, instance:prog.Facebook@c386d]" name="testYahooTest" duration-ms="97580" started-at="2014-09-10T16:07:01Z" finished-at="2014-09-10T16:08:39Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Fail method]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Fail method
	at org.junit.Assert.fail(Assert.java:88)
	at prog.Facebook.testYahooTest(Facebook.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testYahooTest -->
      </class> <!-- prog.Facebook -->
    </test> <!-- order3 -->
  </suite> <!-- TestAll -->
</testng-results>
